name: Build and push docker image to Azure Container Registry

on:
  workflow_call:
    inputs:
      ACR_NAME:
        required: true
        type: string
      AZURE_CLIENT_ID:
        required: true
        type: string
      AZURE_TENANT_ID:
        required: true
        type: string
      AZURE_SUBSCRIPTION_ID:
        required: true
        type: string
      DOCKERFILE_NAME:
        required: false
        type: string
      DOCKERFILE_PATH:
        required: false
        type: string
      ENVIRONMENT:
        required: true
        type: string
      REGISTRY_URL:
        required: true
        type: string
      RETAG:
        required: false
        type: boolean
        default: true
      BUILD_ARG:
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.AZURE_CLIENT_ID }}
          tenant-id: ${{ inputs.AZURE_TENANT_ID }}
          subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
      - name: Login to ACR
        run: |
          az acr login --name ${{ inputs.ACR_NAME }}
      - name: Build and push container image
        if: ${{ (inputs.ENVIRONMENT != 'prod' && (inputs.RETAG == true || inputs.RETAG == 'true')) || (inputs.RETAG == false || inputs.RETAG == 'false') }}
        working-directory: ${{ inputs.DOCKERFILE_PATH }}
        run: |
          docker build -f ${{ inputs.DOCKERFILE_NAME }} \
            -t ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}:$GITHUB_SHA \
            . ${{ inputs.BUILD_ARG }}
          docker push -a ${{ ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}
      - name: Retag and push container image
        if: ${{ inputs.ENVIRONMENT == 'prod' && (inputs.RETAG == true || inputs.RETAG == 'true') }}
        run: |
          docker pull ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}:$GITHUB_SHA
          docker tag ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}:$GITHUB_SHA ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}:${{ github.ref_name }}
          docker push ${{ inputs.ACR_NAME }}.azurecr.io/${{ inputs.APPLICATION_NAME }}:${{ github.ref_name }}