name: Build

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      ARTIFACT_NAME:
        required: false
        type: string
      ARTIFACT_PATH:
        required: false
        type: string
      AWS_ACCOUNT_ID:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_ROLE_NAME:
        required: true
        type: string
      DOCKERFILE_NAME:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      REGISTRY_URL:
        required: true
        type: string
    secrets:
      BUILD_ARG:
        required: false

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.AWS_ROLE_NAME }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Download artifact
        if: ${{ inputs.ARTIFACT_NAME && input.ARTIFACT_PATH }}
        uses: actions/download-artifact@master
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: ${{ input.ARTIFACT_PATH }}
      - name: Build and push container image
        if: ${{ inputs.ENVIRONMENT == 'dev' }}
        working-directory: ${{ inputs.DOCKERFILE_PATH }}
        run: |
          docker build -f ${{ inputs.DOCKERFILE_NAME }} \
            -t ${{ inputs.REGISTRY_URL }}/${{ inputs.APPLICATION_NAME }}:$GITHUB_SHA \
            . ${{ secrets.BUILD_ARG }}
          docker push -a ${{ inputs.REGISTRY_URL }}/${{ inputs.APPLICATION_NAME }}
