name: Deploy to infra

on:
  workflow_call:
    inputs:
      INFRASTRUCTURE_REPO:
        required: true
        type: string
      ARGO_APP_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      GAR_REPO_DOMAIN:
        required: false
        type: string
      GAR_REPO_PATH:
        required: false
        type: string
      SERVICE_ACCOUNT:
        required: false
        type: string
      WORKLOAD_IDENTITY_PROVIDER:
        required: false
        type: string
      
    secrets:
      INFRA_SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        run: |-
          echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c 1-9)" >> $GITHUB_ENV
      
      - name: Set IMAGE_ID
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          echo "IMAGE_ID=${{ inputs.GAR_REPO_DOMAIN }}/${{ inputs.GAR_REPO_PATH }}" >> $GITHUB_ENV

      - id: 'auth'
        if: startsWith(github.ref, 'refs/tags/')
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          workload_identity_provider: ${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ inputs.SERVICE_ACCOUNT }}

      - name: Build and tag Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull ${{ env.IMAGE_ID }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_ID }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_ID }}:${{ github.ref_name}}
          docker push ${{ env.IMAGE_ID }}:${{ github.ref_name}}

      - name: Clone infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.INFRASTRUCTURE_REPO }}
          ref: 'main'
          ssh-key: ${{ secrets.INFRA_SSH_PRIVATE_KEY }}

      - name: Update image tag in values file
        run:
          yq eval -i '.image.tag="${{ env.IMAGE_TAG }}"' 'kubernetes/helm/${{ inputs.ARGO_APP_NAME }}/${{ inputs.ENVIRONMENT }}.values.yaml'
        

      - name: commit changes to image tag
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          git add kubernetes/helm/${{ inputs.ARGO_APP_NAME }}/${{ inputs.ENVIRONMENT }}.values.yaml
          git commit -m "github-action: update image tag to ${{ env.IMAGE_TAG }} by ${GITHUB_ACTOR}"
          git push
