name: Generate Apollo SDL

on:
  workflow_call:
    inputs:
      ECR_REPO_LABEL:
        required: true
        type: string

jobs:
  generate-SDL:
    name: "Generate SDL"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up dependencies
        run: ./setup.sh
        shell: bash

      - name: Generate SDL
        run: |
          . ~/.venvs/${{ inputs.ECR_REPO_LABEL }}/bin/activate
          strawberry export-schema main_server:schema > schema.graphql

      - name: Upload SDL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema_graphl
          path: ./schema.graphql
          retention-days: 2
